# Set OS to linux
os: linux

# Set the build language to Python
language: python

# Set the python version to 3.5
python: 3.5

# Get updates before install
before_install:
  - sudo apt-get update

# Install the library dependencies
install:
  - sudo apt-get install python3
  - pip3 install numpy

# Run python scripts
script:
  python3 main.py 8 8,6,7,2,5,4,3,0,1
